apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
helmCharts:
- name: metrics-server
  releaseName: metrics-server
  version: 3.8.2
  repo: https://kubernetes-sigs.github.io/metrics-server
  valuesInline:
    fullnameOverride: metrics-server