apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- alertmanager-secret-sealed.yaml
- virtual-service.yaml
# - alertmanager-templates.yaml
# - secret-config-sealed.yaml