apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
helmCharts:
- name: devxp-app
  releaseName: devxp-app
  version: 0.1.39
  repo: https://devxp-tech.github.io/helm-charts
  valuesInline:
    name: teste-dpsp
    image:
      repository: ghcr.io/devxp-tech/teste-dpsp
      tag: 52b31b9b
    autoscaling:
      enabled: 
      minReplicas: 
      maxReplicas: 
      targetCPUUtilizationPercentage: 
    resources:
      requests:
        memory: 
        cpu: 
      limits:
        memory: 
        cpu: 