apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rollouts
resources:
- deploy.yaml
- hpa.yaml
- kustomization.yaml
- namespace.yaml
- rollout.yaml
- service.yaml
- virtual-service.yaml