apiVersion: v2
appVersion: 1.0.0
description: Helm Charts for default DevXP-Tech Application
icon: https://github.com/devxp-tech/helm-charts/blob/main/charts/tooling/helm-icon.png
maintainers:
- email: contato@diegoluisi.eti.br
  name: diegoluisi
name: devxp-app
type: application
version: 0.1.62
