apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
helmCharts:
- name: istiod
  releaseName: istiod
  version: 1.14.3
  repo: https://istio-release.storage.googleapis.com/charts
  includeCRDs: true
  valuesInline:
    fullnameOverride: istiod
    global:
      trustDomain: "lgsk8sp1.grupologos.local"
      proxy:
        clusterDomain: "lgsk8sp1.grupologos.local"
      # Resources for the sidecar.
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
      # autoscalingv2API: false
    # meshConfig:
    #   defaultConfig:
    #     discoveryAddress: istiod.istio-system.svc:15012
    # telemetry:
    #   enabled: false
      # configValidation: false