apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: prometheus-policy
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: prometheus
  action: ALLOW
  rules:
    - when:
        - key: request.headers[x-envoy-external-address]
          values:
            - "94.62.74.120" # Diego
      to:
        - operation:
            methods: ["GET", "POST", "OPTIONS", "DELETE", "PATCH"]
    - from:
      - source:
          namespaces:
          - backstage
          - monitoring
          - kiali-operator
      to:
      - operation:
          methods: ["GET", "POST", "OPTIONS", "DELETE", "PATCH"]