apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backstage
resources:
  - ../../base
  - cluster-role.yaml
  - postgres-secrets.yaml
  - postgres-config.yaml
  - sa-token.yaml
  - secrets.yaml
helmCharts:
  - name: devxp-app
    releaseName: devxp-app
    version: 0.2.23
    repo: https://devxp-tech.github.io/helm-charts
    valuesInline:
      global:
        cluster: cluster.local
      name: "backstage"
      image:
        repository: ghcr.io/devxp-tech/backstage
        tag: fb2baddb
      serviceAccount:
        annotations:
          "eks.amazonaws.com/role-arn": "arn:aws:iam::239468932737:role/backstage-lgseksd1-sa"
      quota:
        enabled: false
      container:
        port: 7007
      env:
        - name: ENV
          value: production
      envFrom:
        - configMapRef:
            name: postgres-configs
        - secretRef:
            name: postgres-secrets
        - secretRef:
            name: backstage-secrets
      network:
        domain: devxp-tech.io
      resources:
        requests:
          memory: 400Mi
          cpu: 10m
        limits:
          memory: 1024Mi
          cpu: 200m
      readinessProbe:
        initialDelaySeconds: 15
        periodSeconds: 10
        httpGet:
          port: http
          path: "/healthcheck"
          httpHeaders:
            - name: Host
              value: backstage.devxp-tech.io
      livenessProbe:
        initialDelaySeconds: 15
        periodSeconds: 10
        httpGet:
          port: http
          path: "/healthcheck"
          httpHeaders:
            - name: Host
              value: backstage.devxp-tech.io
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 2
        targetCPUUtilizationPercentage: 80

  # - name: devxp-infra
  #   releaseName: devxp-infra
  #   version: 0.0.3
  #   repo: https://devxp-tech.github.io/helm-charts
  #   valuesInline:
  #     name: "backstage"
  #     Bucket:
  #       enabled: true

  - name: postgresql
    releaseName: postgresql
    version: 12.2.1
    repo: https://charts.bitnami.com/bitnami
    valuesInline:
      commonLabels:
        app: backstage
        version: 15.1.0
      auth:
        username: backstage
        database: backstage
        existingSecret: postgres-secrets
      global:
        postgresql:
          auth:
            database: backstage
            username: backstage
            existingSecret: postgres-secrets
      primary:
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
