apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
helmCharts:
- name: base
  includeCRDs: true
  releaseName: base
  version: 1.14.1
  repo: https://istio-release.storage.googleapis.com/charts
- name: istiod
  includeCRDs: true
  releaseName: istiod
  version: 1.14.1
  repo: https://istio-release.storage.googleapis.com/charts
  valuesInline:
    meshConfig:
      defaultConfig:
        discoveryAddress: istiod.istio-system.svc:15012