apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
helmCharts:
- name: devxp-app
  releaseName: devxp-app
  version: 0.1.30
  repo: https://devxp-tech.github.io/helm-charts
  valuesInline:
    name: teste-devxpapp
    image:
      repository: diegoluisi/teste-devxpapp
      tag: latest
    autoscaling:
      enabled: true
      minReplicas: 
      maxReplicas: 
      targetCPUUtilizationPercentage: 80